minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_id=eln
mod_name=Electrical Age
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=mods.eln
mod_authors=Electrical Age Team
mod_description=Electrical Age for 1.20.1
